/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as RecordIdRouteImport } from './routes/record.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdRoute = RecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/ledger': typeof LedgerRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/ledger': typeof LedgerRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/ledger': typeof LedgerRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/ledger'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/ledger'
    | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/ledger'
    | '/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ConstitutionRoute: typeof ConstitutionRoute
  DeskRoute: typeof DeskRoute
  ExchangeRoute: typeof ExchangeRoute
  InboxRoute: typeof InboxRoute
  LedgerRoute: typeof LedgerRoute
  RecordIdRoute: typeof RecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id': {
      id: '/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof RecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ConstitutionRoute: ConstitutionRoute,
  DeskRoute: DeskRoute,
  ExchangeRoute: ExchangeRoute,
  InboxRoute: InboxRoute,
  LedgerRoute: LedgerRoute,
  RecordIdRoute: RecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
