/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChamberRouteImport } from './routes/chamber'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ValuesRouteImport } from './routes/values'
import { Route as RecordIdRouteImport } from './routes/record.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRoute = ChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuesRoute = ValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIdRoute = RecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ask': typeof AskRoute
  '/chamber': typeof ChamberRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/values': typeof ValuesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ask': typeof AskRoute
  '/chamber': typeof ChamberRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/values': typeof ValuesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ask': typeof AskRoute
  '/chamber': typeof ChamberRoute
  '/constitution': typeof ConstitutionRoute
  '/desk': typeof DeskRoute
  '/exchange': typeof ExchangeRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/values': typeof ValuesRoute
  '/record/$id': typeof RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ask'
    | '/chamber'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/insights'
    | '/ledger'
    | '/library'
    | '/privacy'
    | '/terms'
    | '/values'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ask'
    | '/chamber'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/insights'
    | '/ledger'
    | '/library'
    | '/privacy'
    | '/terms'
    | '/values'
    | '/record/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ask'
    | '/chamber'
    | '/constitution'
    | '/desk'
    | '/exchange'
    | '/inbox'
    | '/insights'
    | '/ledger'
    | '/library'
    | '/privacy'
    | '/terms'
    | '/values'
    | '/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AskRoute: typeof AskRoute
  ChamberRoute: typeof ChamberRoute
  ConstitutionRoute: typeof ConstitutionRoute
  DeskRoute: typeof DeskRoute
  ExchangeRoute: typeof ExchangeRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  LedgerRoute: typeof LedgerRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ValuesRoute: typeof ValuesRoute
  RecordIdRoute: typeof RecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/values': {
      id: '/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof ValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$id': {
      id: '/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof RecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AskRoute: AskRoute,
  ChamberRoute: ChamberRoute,
  ConstitutionRoute: ConstitutionRoute,
  DeskRoute: DeskRoute,
  ExchangeRoute: ExchangeRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  LedgerRoute: LedgerRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ValuesRoute: ValuesRoute,
  RecordIdRoute: RecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
